### PR TITLE
test: add test coverage and example usage for HIP719 isAssociated()

### LINKED ISSUE #861: Add tests for calling isAssociated() via HRC proxy contract
### Problem

Until recently calling isAssociated() was not possible, but now with the resolving of [this](https://github.com/hashgraph/hedera-services/issues/5950) issue in services, this is possible.

### Solution

We'd need to extend our current examples to support and test this behaviour.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by Ivo-Yankov**
**Description**:

This PR adds test coverage and an example usage of `isAssociated()` in the `@HRC-719 Test Suite`.

Since `isAssociated()` is fully supported in Services but not yet in the Mirror Node due to the ongoing Web3 module rework, the feature has been invoked in non-view functions as a workaround. This ensures the execution is handled by the Consensus Node rather than the Mirror Node.

```solidity
function isAssociated(address token) public {
    bool status = IHRC719(token).isAssociated();
    emit IsAssociated(status);
}
```

Once the Web3 module rewrite is complete, this workaround should be reverted to a regular view function to avoid unnecessary fees for the caller. This issue is tracked by this ticket https://github.com/hashgraph/hedera-smart-contracts/issues/948.

Fixes #861

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by lukelee-sl — DISMISSED** [review]
LGTM

**Review by Nana-EC — APPROVED** [review]
Nice work

**Comment by Nana-EC** [comment]
@mshakeg heads up.
We're adding tests to capture isAssociated() from HIP 719

**Review by Nana-EC — COMMENTED** [review]
Should also update https://github.com/hashgraph/hedera-smart-contracts/tree/main/contracts/system-contracts/hedera-token-service with isAssociated - HIP 719 - 0.53

**Review by Nana-EC — APPROVED** [review]

**Review by Ivo-Yankov — COMMENTED** [review]
LGTM

**Pull request merged**
