### PR TITLE
removed all uses of uints from hedera token service selectors

### PR DESCRIPTION
**Pull request by georg-getz**
Signed-off-by: Georgi Georgiev <georgi.getz@outlook.com>

**Description**:
This PR removes usages of uints in the HederaTokenService interface and contract and any necessary follow up changes in the other files.

**Related issue(s)**:
hashgraph/hedera-protobufs#235
hashgraph/hedera-services#4067

Fixes hashgraph/hedera-services#3916 and #85

**Important note**
Tests aren't passing because of 2 reasons:
1. In order for them to pass the related issue in hedera services needs to be merged so that selectors are updated
2. They currently don't pass in main branch either

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by georgi-l95 — COMMENTED** [review]
LG, but I think that, we should apply those changes in the examples as well. Because of that the test are not passing.

**Review by Nana-EC — APPROVED** [review]
LG.

**Review by IvanKavaldzhiev — DISMISSED** [review]
LGTM

**Review by shemnon — APPROVED** [review]

**Comment by Nana-EC** [comment]
@georg-getz can rebase and we can sign off

**Review by shemnon — DISMISSED** [review]

**Review by georgi-l95 — APPROVED** [review]
LGTM!

**Pull request closed without merging**
