### PR TITLE
Update contracts.maxNumWithHapiSigsAccess to 0 and update test

### LINKED ISSUE #235: Update contracts.maxNumWithHapiSigsAccess to 0 and update tests
Update the local node property contracts.maxNumWithHapiSigsAccess to 0 and update tests respectively

### PR DESCRIPTION
**Pull request by natanasow**
**Description**:

After security fixes, the end signer cannot call a contract that executes a precompiled call. 

The signer has to give permission to the contract, making a `KeyList` of the signer's public key and contract's addresses as `contractId` key type.
```
// Account keys 
KeyList([signer.publicKey, contract1.address, contract2.address])
```

If the signer wants to modify the token, the token keys have to be updated to `KeyList` of the public key of all signers, and the address as `contractId` of all contracts via token update will be performed.
```
// Token keys
KeyList([signer1.publicKey, signer2.publicKey, contract1.address, contract2.address]);
```

**Related issue(s)**:

Fixes #235 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by ebadiere — APPROVED** [review]
LG.

**Comment by Nana-EC** [comment]
@natanasow can you update the images again. I think we should be good once you do that.
`maxNumWithHapiSigsAccess` should now default to 0 with 0.39.0 and onwards

**Review by Nana-EC — APPROVED** [review]
LG

**Review by ebadiere — APPROVED** [review]
LG.  I'd like to see how this runs in CI.

**Pull request merged**
