### PR TITLE
Add `transferFrom` support in `IHederaTokenService`

### LINKED ISSUE #70: Add new `transferFrom` functions to the HTS precompile
With https://github.com/hashgraph/hedera-services/issues/3904 implemented, we have new functions in the HTS precompile. We should add those to the solidity files.

### PR DESCRIPTION
**Pull request by dimitar-dinev**
**Description**:

* Adds `transferFrom` and `transferFromNFT` (equivalents of ERC20/721 `transferFrom`) to `IHederaTokenService`.

**Related issue(s)**:

Fixes #70

### CODE REVIEW

**Review by Nana-EC — APPROVED** [review]
LG, once merged we'll also need a PR to update HIP 514 with the method and hash reference

**Review by shemnon — DISMISSED** [review]

**Comment by dimitar-dinev** [comment]
Force pushed to fix commit signatures.

**Comment by stoqnkpL** [comment]
@dimitar-dinev force pushed to fix DCO, can we get a reapprove @shemnon @Nana-EC

**Review by Nana-EC — APPROVED** [review]

**Comment by stoqnkpL** [comment]
Actually, we won't be able to merge this ourselves:
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

**Review by shemnon — APPROVED** [review]

**Pull request merged**
